### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by madskristensen** [marcominerva/AlexaSkillTemplate#5]
On the Marketplace, it is hard to figure out what exactly this project template generates. I would be super helpful with a screenshot of Solution Explorer so you get a feel for how many projects, what type of projects etc.

**Comment by marcominerva** [comment]
Thank you for your suggestion! I have added a couple of screenshot either in the README.md file and on the MarketPlace. I plan to add more information about the template in the next few days.

**Comment by madskristensen** [comment]
Nice!
